shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('products/<slug:category>/<slug:product>/',
         views.info_product, name='info_product'),
    path('products/', views.list_categories, name='list_categories'),
    path('products/<slug:category>/',
         views.category_products, name='category_products'),
]

shop_cm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(
        max_length=200, verbose_name='Имя категории')
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class Product(models.Model):
    LITER = "л"
    KILOGGRAM = "кг"
    MEASURMENT_UNIT_CHOICES = [
        (LITER, 'литр'),
        (KILOGGRAM, 'килограмм'),
    ]

    product_name = models.CharField(max_length=200, verbose_name='Имя товара')
    slug = models.SlugField(max_length=200)
    category = models.ForeignKey(
        Category, related_name='category', on_delete=models.CASCADE, verbose_name='Категория')
    image = models.ImageField(upload_to='products/',
                              verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10,
                                decimal_places=2, verbose_name='Цена')
    min_volume = models.DecimalField(max_digits=3,
                                     decimal_places=2, verbose_name='Мин. кол-во')
    aging = models.DecimalField(
        max_digits=2, decimal_places=1, verbose_name='Выдержка', default=0)
    unit = models.CharField(max_length=2,
                            choices=MEASURMENT_UNIT_CHOICES, default=KILOGGRAM, verbose_name='Ед. измерения')
    available = models.BooleanField(default=True, verbose_name='Доступность')
    create = models.DateField(default=date.today, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Товары'
        verbose_name_plural = 'Товары'
        ordering = ['category']

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        print('прошло')
        category = Category.objects.get(id=self.category_id)
        print('Прошло')
        return reverse('shop:info_product', args=[category.slug, self.slug])

shop/views.py
from django.shortcuts import render
from .models import Product, Category


def main_page(request):
    return render(request, 'shop/main/main_page.html')


def list_categories(request):
    products_list = Category.objects.all()
    return render(request, 'shop/main/products.html',
                  {'products': products_list})


def category_products(request, category):
    category = Category.objects.get(slug=category)
    products = Product.objects.filter(category=category.id)
    return render(request, 'shop/main/category_products.html',
                  {'products': products,
                   'category': category})


def info_product(request, category, product):
    product = Product.objects.get(slug=product)
    return render(request, 'shop/main/info_product.html',
                  {'product': product})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>

    <link href="{% static 'shop/css/base.css' %}" type="text/css" rel="stylesheet">
</head>

<body>
    <div class="overlay">
        Продукция
    </div>
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

shop/templates/shop/main/category_products.html
{% extends 'shop/base.html' %}

{% block title %}
{{category.category_name}}
{% endblock title %}



{% block content %}

{% for product in products %}
<a href="{% url 'shop:info_product' category.slug product.slug%}">{{product}}</a>

{% endfor %}

{% endblock content %}

shop/templates/shop/main/info_product.html
{% extends 'shop/base.html' %}


{% block title %}
{{product.product_name}}
{% endblock title %}



{% block content %}
<img src="{{product.image.url}}">
{{product.product_name}}
{{product.description}}
{{product.price}}
{% endblock content %}

shop/templates/shop/main/main_page.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
Цельское молочко
{% endblock title %}

{% block content %}
<nav>
    <ul>
        <li><a href="{% url 'shop:list_categories' %}">Продукция</a></li>
        <li><a href="#">О нас</a></li>
        <li><a href="#">Услуги</a></li>
        <li><a href="#">Контакты</a></li>
    </ul>
</nav>

{% endblock content %}

shop/templates/shop/main/products.html
{% extends 'shop/base.html' %}


{% block title %}
Категории продуктов
{% endblock title %}



{% block content %}

{% for product in products %}
<a href="{% url 'shop:category_products' product.slug%}">{{product}}</a>
{% endfor %}

{% endblock content %}